language: php

matrix:
    include:
        - php: 7.1
        - php: 7.0
          env: CS_FIXER=true
        - php: 5.6
        - php: 5.5
        - php: 5.4
    fast_finish: true

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
    # We need to use our modified version until the fixers are merged upstream.
    - "export FIXER_REPO=--repository='{\"type\": \"vcs\", \"url\": \"https://github.com/jtojnar/php-cs-fixer\"}'"
    - if [ "$CS_FIXER" = true ]; then composer create-project --no-dev --no-interaction "$FIXER_REPO" friendsofphp/php-cs-fixer utils/php-cs-fixer dev-selfoss; fi
    - composer create-project --no-dev --no-interaction jakub-onderka/php-parallel-lint utils/php-parallel-lint

script:
    - utils/php-parallel-lint/parallel-lint src
    - if [ "$CS_FIXER" = true ]; then utils/php-cs-fixer/php-cs-fixer fix --verbose --dry-run; fi
